module.exports = {
  'env': { 'es6': true },
  'rules': {
    'array-bracket-newline': 'off',
    'array-bracket-spacing': ['error', 'never'],
    'array-element-newline': ['warning', 'consistent'],
    'block-spacing': ['error', 'never'],
    'brace-style': ['error', '1tbs', { 'allowSingleLine': true }],
    'camelcase': ['error', 'always', { 'allow': ['^UNSAFE_'] }],
    'capitalized-comments': 'off',
    'comma-dangle': ['error', 'always-multiline'],
    'comma-spacing': ['error', { 'after': true }],
    'comma-style': ['error', 'last'],
    'computed-property-spacing': ['error', 'never'],
    'consistent-this': ['error', 'self'],
    'eol-last': ['error', 'always'],
    'func-call-spacing': 'off',
    'func-name-matching': ['error', 'as-needed'],
    'func-names': 'off',
    'func-style': ['error', 'declaration'],
    'function-paren-newline': ['error', 'multiline'],
    'id-blacklist': 'off',
    'id-length': 'off',
    'id-match': 'off',
    'implicit-arrow-linebreak': 'off',
    'indent': ['error', 'tab'],
    'jsx-quotes': ['error', 'prefer-single'],
    'key-spacing': ['error', { 'beforeColon': false, 'afterColon': true, 'mode': 'strict' }],
    'keyword-spacing': ['error', { 'before': true, 'after': true }],
    'line-comment-position': 'off',
    'linebreak-style': ['error', 'unix'],
    'lines-around-comment': 'off',
    'lines-between-class-members': ['error', 'always'],
    'max-depth': ['error', { 'max': 3 }],
    'max-len': ['error', { 'code': 80 }],
    'max-lines': 'off',
    'max-lines-per-function': ['warning', 50],
    'max-nested-callbacks': 'off',
    'max-params': ['warning', 5],
    'max-statements': 'off',
    'max-statements-per-line': ['error', { 'max': 1 }],
    'multiline-comment-style': 'off',
    'multiline-ternary': ['error', 'always-multiline'],
    'new-cap': 'off',
    'new-parens': ['error'],
    'newline-per-chained-call': ['warning', { 'ignoreChainWithDepth': 2 }],
    'no-array-constructor': ['error'],
    'no-bitwise': ['error'],
    'no-continue': ['error'],
    'no-inline-comments': 'off',
    'no-lonely-if': ['error'],
    'no-mixed-operators': ['error'],
    'no-mixed-spaces-and-tabs': ['error'],
    'no-multi-assign': ['error'],
    'no-multiple-empty-lines': ['error', { 'max': 1, 'maxEOF': 1, 'maxbOF': 0 }],
    'no-negated-condition': 'off',
    'no-nested-ternary': 'off', // not sure about this
    'no-new-object': ['error'],
    'no-plusplus': 'off',
    'no-restricted-syntax': 'off',
    'no-tabs': ['error', { allowIndentationTabs: true }],
    'no-ternary': 'off',
    'no-trailing-spaces': ['error'],
    'no-underscore-dangle': 'off',
    'no-unneeded-ternary': ['error'],
    'no-whitespace-before-property': ['error'],
    'nonblock-statement-body-position': 'off',
    'object-curly-newline': ['error', { 'multiline': true }],
    'object-curly-spacing': ['error', 'never'],
    'object-property-newline': 'off',
    'one-var': 'off',
    'one-var-declaration-per-line': 'off',
    'operator-assignment': ['error', 'always'],
    'operator-linebreak': ['error', 'before'],
    'padded-blocks': ['error', 'never'],
    'padding-line-between-statements': 'off', // to much stuff to think about
    'prefer-object-spread': 'off',
    'quote-props': ['error', 'as-needed'],
    'quotes': ['error', 'single', { 'avoidEscape': true }],
    'require-jsdoc': 'off',
    'semi': ['error', 'never'],
    'semi-spacing': ['error', { 'before': false, 'after': true }],
    'semi-style': ['error', 'last'],
    'sort-keys': ['warning', 'asc', { natural: true }],
    'sort-vars': 'off',
    'space-before-blocks': ['error', 'always'],
    'space-before-function-paren': ["error", "never"],
    'space-in-parens': ["error", "never"],
    'space-infix-ops': ["error"],
    'space-unary-ops': ['error'],
    'spaced-comment': ['error', 'always'],
    'switch-colon-spacing': ['error', { after: true, before: false }],
    'template-tag-spacing': ['error', 'never'],
    'unicode-bom': 'off',
    'wrap-regex': 'off',
  },
};
